### PR TITLE
Regix search for values

### PR DESCRIPTION
**Pull request by subashz**
Some botton changes and file search values.

### CODE REVIEW

**Comment by daedreth** [comment]
What precisely is the point of the 2 buttons you added? I don't see how it's different from the "save" options in the menu.

The regix search breaks the transparencyslider.

Thanks for the improvements tho

**Comment by subashz** [comment]
Its easier to apply the change from those button. Its quicker and faster. :)

**Comment by daedreth** [comment]
Is the change via xrdb persistent, or does it only work until the X server is restarted?

**Comment by subashz** [comment]
Its persistent. Yes it works after xserver restarted !

**Comment by daedreth** [comment]
I see it is saving to .Xresources.

Originally, this app had buttons where  you placed them (hence the empty space), due to user feedback however I decided to steer clear from one default location for the file and give the user the ability to save and load settings from precisely where they want to.

**Comment by subashz** [comment]
Can you point me where the regix breaks the transparency slider. I searched for a while but cannot find .. where ?? Line number will be helpful

**Comment by daedreth** [comment]
I can not debug this as I'm not home, but here is what happens.

The way true transparency works is, we specify .background: in the file once again, but start the hex color with a " [n] ", where n is the value of how transparent you'd like it to be.

to reproduce, just save to file with true transparency enabled and a value on the spinBox, and try to reload it.

**Comment by daedreth** [comment]
The buttons are a deprecated attempt at this and offer no customizability that was wished for by the users.

A simple .startsWith is much easier to modify and maintain than QRegExp statements.
The way this works will be changed to allow for larger tolerance of older, written by the user configuration files.

The change I agree with and enjoy is updating the preview on font resize.

**Comment by subashz** [comment]
That will be fine for me.

**Pull request closed without merging**
